config/routes.rb
Rails.application.routes.draw do
  root 'orders#index'
  get '/myorders', to: 'orders#myorders'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :items
  resources :orders do
    member do
        patch 'update_acceptance'
    end

  end

  resources :restaurants
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  has_many :items
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  #a user could be not a restaurant so would not have one
  has_many :restaurants
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @restaurant_name = Restaurant.where(:id=>:restaurant_id)
    # @items = Item.where(:order_id=)
  end

  #adding for my orders
  def myorders
    @orders = Order.all
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  def update_acceptance
    @order = set_order
    @order.update({"accepted" => true})
    redirect_back(fallback_location: current_user)

    #   format.html { redirect_to @order, notice: 'Order was successfully accepted.' }
    # }
    # format.json { render :show, accepted: :true, location: @order }
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = current_user.orders.new(order_params)
    @order.update({"orderedat" => Time.now})

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:restaurant_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:isRestaurant, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:isRestaurant, :email, :password, :password_confirmation, :current_password)
  end

  def isRestaurant
    @user.isRestaurant
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = current_user.restaurants.new(restaurant_params)
    current_user.restaurant_ids = @restaurant_id
    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :city)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.number_field :order_id, id: :item_order_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :item_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.order_id %></td>
        <td><%= item.name %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @item.order_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<style>
input[type=text], input[type=password], input[type=email], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
}

input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

input[type=submit]:hover {
    background-color: #45a049;
}

div {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
}
</style>
<html>
  <head>
    <title>Food</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <nav class="navbar navbar-default">
  <div class="container-fluid">

    <ul class="nav navbar-nav">
      <% if user_signed_in? %>


        <% if current_user.isRestaurant %>
        <div class="navbar-header">
        <a class="navbar-brand" href="/orders">Fran's Food Restaurant Style</a>
        </div>

        <li class="active"><a href="/orders">Everyone's Orders</a></li>
        <li><a href="/myorders">Your Order History</a></li>
        <% if current_user.restaurants.empty? %>
          <li><a href="/restaurants/new">You're a new and need to add restaurant to the list of restaurant</a></li>
        <% else %>
        <% end %>

        <% else %>
        <div class="navbar-header">
        <a class="navbar-brand" href="/orders">Fran's Food</a>
        </div>
        <li class="active"><a href="/orders">Everyone's Orders</a></li>
        <li><a href="/myorders">Your Order History</a></li>
        <li><a href="/restaurants">Restaurants</a></li>
        <li><a href="/orders/new">Create Order</a></li>
        <% end %>
        <li> <%= link_to 'Logout', destroy_user_session_path, method: :delete %> </li>
        <% else %>
      <% end %>
    </ul>
  </div>
  </nav>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>



    </div>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :order_user_id %>
  </div> -->
  <h5>Choose Restaurant From pullDown flap</h5>


  <div class="field">
    <%= form.label :restaurant_id %><br>
    <%= form.collection_select(:restaurant_id, Restaurant.all, :id, :name) %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<h1>Orders</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Restaurant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.user.email %></td>
        <td><%= order.restaurant.name %></td>
        <td><%= link_to 'Show', order %></td>
        <% if current_user.email.eql?('penad@seas.upenn.edu') %>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>

        <td> <button type="button" class="btn btn-danger"><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></button>

        <% else %>
        <% end %>


        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/myorders.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Orders</h1>
<!-- if user is resutant should be different
 -->
<% if current_user.isRestaurant %>
  <table class="table table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Restaurant</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <h2> PENDING ORDERS </h2>
    <% @orders.each do |order| %>
    <% if order.restaurant_id.eql?(current_user.restaurants.ids[0]) %>
      <tr>
        <% if order.accepted.eql?(false) %>
        <td><%= order.user.email %></td>
        <td><%= order.restaurant.name %></td>
        <td><%= order.orderedat %></td>

        <td><%= link_to 'Show', order %></td>

        <td> <button type="button" class="btn btn-success"><%= link_to 'Accept',update_acceptance_order_path(order), method: :patch, data: { confirm: 'You are accepting order'} %></button></td>

        <td> <button type="button" class="btn btn-danger"><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>

        <% else %>
      <% end %>
      </tr>
      <% else %>
      <% end %>
    <% end %>
  </tbody>
</table>

<table class="table table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Restaurant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <h2> Accepted Orders </h2>
    <% @orders.each do |order| %>
    <% if order.restaurant_id.eql?(current_user.restaurants.ids[0]) %>
      <tr>
        <% if order.accepted.eql?(true) %>

        <td><%= order.user.email %></td>
        <td><%= order.restaurant.name %></td>
        <td><%= order.orderedat %></td>

        <td><%= link_to 'Show', order %></td>


        </td>
        <% else %>
        <% end %>
      </tr>
      <% else %>
      <% end %>
    <% end %>
  </tbody>
</table>
<!-- A NORMAL USER  -->
<% else %>
 <table class="table table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Restaurant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <h2> Pending Orders </h2>
    <% @orders.each do |order| %>
    <% if order.user_id.eql?(current_user.id) %>
      <tr>
        <% if order.accepted.eql?(false) %>
        <td><%= order.user.email %></td>
        <td><%= order.restaurant.name %></td>
        <td><%= order.orderedat %></td>

        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>

        <td> <button type="button" class="btn btn-danger"><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></button>

        </td>
        <% else %>
        <% end %>
      </tr>

      <% else %>
      <% end %>
    <% end %>
  </tbody>
</table>

<!-- ACCEPTED ORDERS -->
<table class="table table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Restaurant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <h2> Accepted Orders </h2>
    <% @orders.each do |order| %>
    <% if order.user_id.eql?(current_user.id) %>
      <tr>
        <% if order.accepted.eql?(true) %>

        <td><%= order.user.email %></td>
        <td><%= order.restaurant.name %></td>
        <td><%= order.orderedat %></td>

        <td><%= link_to 'Show', order %></td>


        </td>
        <% else %>
         <% end %>
      </tr>
      <% else %>
      <% end %>
    <% end %>
  </tbody>
</table>


<% end %>

app/views/orders/new.html.erb
<div class="container">

<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<!-- <p>
  <strong>User:</strong>
  <%= @order.user_id %>
</p> -->

<p>
  <strong>Restaurant:</strong>
  <%= @order.restaurant_id %>
</p>
<h4>Order Items</h4>
  <% @items.each do |item| %>
    <ul>
      <li><%= item.name %></li>
    </ul>
  <% end %>
<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/restaurants/_form.html.erb
<div class="container">
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :restaurant_name %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :restaurant_city %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>
  <table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.city %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <% if current_user.email.eql?('penad@seas.upenn.edu') %>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>

        <td> <button type="button" class="btn btn-danger"><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></button>

        <% else %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.email.eql?('penad@seas.upenn.edu') %>
  <button type="button" class="btn btn-success">
  <%= link_to 'New Restaurant', new_restaurant_path %>
  </button>
<% else %>
<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @restaurant.city %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>